#!/bin/env python

######
# $Id: domhub-services,v 1.2 2004/07/30 02:29:44 kaeld Exp $
######

from SimpleXMLRPCServer import SimpleXMLRPCServer;
from icecube.domtest.dor import Driver
import sys

port = 7501

print >>sys.stderr, "Opening DOMHub service on port", port

server = SimpleXMLRPCServer(('', port))
server.register_instance(Driver())
server.serve_forever()

